import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, officiis! Doloribus odio beatae ipsa modi assumenda eius blanditiis tempora. Officia pariatur reprehenderit, ut commodi possimus quae voluptates minus porro culpa?
      </main>


    </div>
  )
}
